### ISSUE TITLE
Does this repo need to be renamed?

### ISSUE THREAD

**Issue by aidanheerdegen** [mom-ocean/FMS#6]
Hi @underwoo, @marshallward 

Now that MOM6 has become a fully-fledged community model and is housed in the mom-ocean organisation does this fork of FMS need to be renamed to avoid confusion?

Possible candidates could be `FMS-MOM5` to reflect what it is use for or `FMS1` to highlight this is an older version of FMS.

Oh, and welcome to the family!

**Comment by marshallward** [comment]
I agree that we should probably do something to distinguish them.  Some options:
* Rename the repo, as you suggest
* Define a MOM5 branch

Perhaps in the future MOM5 could run under the new FMS API but that day is certainly not today.

**Comment by marshallward** [comment]
I agree that we should probably do something to distinguish them.  It's going to be confusing for people who aren't following explicit instructions.

Some options:

* Rename the repso, as you suggest
* Upload as a new (unforked) repository under the new name.
  - This would allow us to fork the existing FMS if useful
* Keep it as is, but define a MOM5 branch, and possibly set it as default.

We probably want to discuss this at a MOM6 dev call.  I don't know how which FMS repository the other groups are currently using.

Perhaps in the future MOM5 could run under the new FMS API but that day is certainly not today.

**Comment by aidanheerdegen** [comment]
> We probably want to discuss this at a MOM6 dev call. I don't know how which FMS repository the other groups are currently using.

I agree you need to talk about this amongst the MOM6 community. Just let me know the outcome of that when the time comes.

I may be mistaken, but isn't it unlikely there will ever be an official FMS repo house here? That will stay as GFDL in-house, right? 

Might you want to leave open the option to have an "official fork" here, if there is community code changes to FMS?

> Perhaps in the future MOM5 could run under the new FMS API but that day is certainly not today.

I honestly can't see it happening. I forked at the point I did, which is a fair bit before FMS2 stuff, because there were changes to drivers. This would require a fair bit of work for all the old drivers etc, which I'm not sure anyone has the time or motivation to do.

**Comment by marshallward** [comment]
FMS will probably always stay within the NOAA-GFDL GitHub group.  It is a core component of other GFDL models such as FV3, so it would be a strange fit for mom-ocean.

I think an "official fork" is a possibility, but the default branch could only be set to either MOM5 or MOM6, and I don't really think that is an easy decision.

I agree that MOM5 will probably never run under the latest FMS.  Mostly just wishful thinking to avoid a harder decision.

I think right now there's no expectation for MOM6 to have a dedicated FMS repo in mom-ocean.  I'll talk to others, but for now I think it's fine to leave it as is.

**Comment by aidanheerdegen** [comment]
Ok. Thanks. Once you've talked to the other MOM6 folks feel free to update this issue, particularly if we need to rename.

I am in the process of adding some CI to the repo, I will try and remember to update the README so it has some information about this repo and it's status.

**Comment by marshallward** [comment]
I've talked about this with the GFDL MOM6 group, and we agreed that it's OK to leave this repository as it is.

MOM6 does not coordinate releases with FMS, and there has never been any expectation that MOM6 would work under the newest or default FMS branch, so the situation is no different here.

Also, other groups provide their own instructions for linking to FMS, and often do not use the same branch or tag as GFDL.  Many of them also  so another FMS fork at mom-ocean is not a problem.  Many groups even manage their own FMS forks.

It may be useful if this repo keeps a branch supported by MOM6, but even then I don't think it's necessary.

**Comment by aidanheerdegen** [comment]
Okey doke. Thanks for getting back to me. I've also updated the README with some information about this fork in my latest PR.
